"""English voiceover with Sarvam AI Bulbul v3 (Indian English), one file per line, plus word timings.

    SARVAM_API_KEY=... python3 launch/voice.py launch/script.json out/launch-vo [--speaker ritu] [--pace 1.0]

The key is read from the environment only. Word timings come from faster-whisper and are written to
launch/timing.js, so the picture and the captions follow the voice.
"""
import argparse, base64, io, json, os, pathlib, urllib.request, wave
import numpy as np

ap = argparse.ArgumentParser()
ap.add_argument("script"); ap.add_argument("out")
ap.add_argument("--speaker", default="ritu"); ap.add_argument("--pace", type=float, default=1.0)
ap.add_argument("--only", help="regenerate just this line id; keep the others")
a = ap.parse_args()
SR = 24000
out = pathlib.Path(a.out); out.mkdir(parents=True, exist_ok=True)

def tts(text):
    body = {"text": text, "target_language_code": "en-IN", "model": "bulbul:v3", "speaker": a.speaker,
            "pace": a.pace, "speech_sample_rate": SR}
    req = urllib.request.Request("https://api.sarvam.ai/text-to-speech", data=json.dumps(body).encode(),
        headers={"api-subscription-key": os.environ["SARVAM_API_KEY"], "Content-Type": "application/json"})
    w = wave.open(io.BytesIO(base64.b64decode(json.load(urllib.request.urlopen(req, timeout=120))["audios"][0])))
    x = np.frombuffer(w.readframes(w.getnframes()), "<i2").astype(np.float32) / 32768
    return x.reshape(-1, w.getnchannels()).mean(axis=1)

def trim(x):
    idx = np.where(np.abs(x) > 0.02 * np.abs(x).max())[0]
    return x[max(0, idx[0] - int(0.01 * SR)) : idx[-1] + int(0.06 * SR)]

script = json.load(open(a.script))
lp = out / "lengths.json"
lengths = json.load(open(lp)) if (a.only and lp.exists()) else {}
for line in script:
    if a.only and line["id"] != a.only:
        continue
    x = trim(tts(line["text"]))
    with wave.open(str(out / f"{line['id']}.wav"), "wb") as w:
        w.setnchannels(1); w.setsampwidth(2); w.setframerate(SR)
        w.writeframes((np.clip(x, -1, 1) * 32767).astype("<i2").tobytes())
    lengths[line["id"]] = round(len(x) / SR, 3)
    print(f"{line['id']:7s} {lengths[line['id']]:5.2f}s")
json.dump(lengths, open(out / "lengths.json", "w"), indent=1)

from faster_whisper import WhisperModel
m = WhisperModel("base.en", device="cpu", compute_type="int8")
words = {}
for line in script:
    segs, _ = m.transcribe(str(out / f"{line['id']}.wav"), beam_size=5, word_timestamps=True)
    words[line["id"]] = [[w.word.strip(), round(w.start, 3), round(w.end, 3)] for s in segs for w in s.words]
    print(f"  heard [{line['id']}]: {' '.join(x[0] for x in words[line['id']])}")
here = pathlib.Path(__file__).parent
(here / "timing.js").write_text("// generated by launch/voice.py\nwindow.VO_TIMING = " + json.dumps(
    {"lengths": lengths, "words": words, "script": {l["id"]: l["text"] for l in script}}) + ";\n")
print("total speech", round(sum(lengths.values()), 2), "s")
