"""Word timestamps for the voiceover, written to explainer/timing.js so the picture can follow the voice.

    python3 explainer/align.py out/vo

Uses faster-whisper (base.en). Re-run after regenerating or replacing any voiceover line.
"""
import json
import pathlib
import sys

from faster_whisper import WhisperModel

vo = pathlib.Path(sys.argv[1])
here = pathlib.Path(__file__).parent
script = json.load(open(here / "script.json"))
lengths = json.load(open(vo / "lengths.json"))
m = WhisperModel("base.en", device="cpu", compute_type="int8")
words = {}
for line in script:
    segs, _ = m.transcribe(str(vo / f"{line['id']}.wav"), beam_size=5, word_timestamps=True)
    words[line["id"]] = [[w.word.strip(), round(w.start, 3), round(w.end, 3)] for s in segs for w in s.words]
data = {"lengths": lengths, "words": words}
(here / "timing.js").write_text("// generated by explainer/align.py\nwindow.VO_TIMING = " + json.dumps(data) + ";\n")
print("wrote", here / "timing.js")
