"""Generate a voiceover from segmented lines and write exact anchor times for the picture.

    python3 explainer/voice_segments.py explainer/script-hi.json out/vo-hi explainer/timing-hi.js [--voice hf_alpha]

Each line is spoken segment by segment (Kokoro, Apache-2.0) and joined with short pauses, so the start
of every anchored segment is known exactly; no speech recognition is needed for timing. Used for the
Hindi / Hinglish voiceover, where the words that carry each beat fall in a different order than in English.
"""
import argparse
import json
import os
import pathlib

import numpy as np
import soundfile as sf
from kokoro_onnx import Kokoro

ap = argparse.ArgumentParser()
ap.add_argument("script")
ap.add_argument("out")
ap.add_argument("timing")
ap.add_argument("--voice", default="hf_alpha")
ap.add_argument("--lang", default="hi")
ap.add_argument("--speed", type=float, default=1.0)
a = ap.parse_args()

d = pathlib.Path(os.environ.get("KOKORO_DIR", "/tmp/kokoro"))
k = Kokoro(str(d / "kokoro-v1.0.onnx"), str(d / "voices-v1.0.bin"))
out = pathlib.Path(a.out)
out.mkdir(parents=True, exist_ok=True)


def trim(x, sr):
    thr = 0.01 * np.abs(x).max()
    idx = np.where(np.abs(x) > thr)[0]
    return x[max(0, idx[0] - int(0.01 * sr)) : idx[-1] + int(0.04 * sr)]


def pause_after(text):
    t = text.strip()
    if t.endswith(("।", "?", ".", "!")):
        return 0.26
    if t.endswith(","):
        return 0.14
    return 0.05


lengths, words = {}, {}
for line in json.load(open(a.script)):
    parts, anchors, pos, sr = [], [], 0.0, 24000
    segs = line["segments"]
    for i, seg in enumerate(segs):
        audio, sr = k.create(seg["text"], voice=a.voice, speed=a.speed, lang=a.lang)
        audio = trim(audio, sr)
        if i > 0:
            gap = seg.get("gap", pause_after(segs[i - 1]["text"]))
            parts.append(np.zeros(int(gap * sr), dtype=audio.dtype))
            pos += gap
        if seg.get("anchor"):
            anchors.append([seg["anchor"], round(pos, 3), round(pos + len(audio) / sr, 3)])
        parts.append(audio)
        pos += len(audio) / sr
    full = np.concatenate(parts)
    sf.write(out / f"{line['id']}.wav", full, sr)
    lengths[line["id"]] = round(len(full) / sr, 3)
    words[line["id"]] = anchors
    print(f"{line['id']:8s} {lengths[line['id']]:5.2f}s  " + " ".join(f"{n}@{s}" for n, s, _ in anchors))
json.dump(lengths, open(out / "lengths.json", "w"), indent=1)
pathlib.Path(a.timing).write_text(
    "// generated by explainer/voice_segments.py\nwindow.VO_TIMING = " + json.dumps({"lengths": lengths, "words": words}, ensure_ascii=False) + ";\n"
)
print("total speech", round(sum(lengths.values()), 2), "s ->", a.timing)
