"""Generate the Hinglish voiceover with Sarvam AI's Bulbul (built for Indian languages and code-mixed speech).

    SARVAM_API_KEY=... python3 explainer/voice_sarvam.py explainer/script-hinglish.json out/vo-hinglish explainer/timing-hinglish.js

The key is read from the environment only; never commit it. Each clause is spoken whole (natural
prosody) and clauses are joined with short pauses. Anchors are written inline as {name}: an anchor at the
start of a clause is exact; one inside a clause is placed by its syllable position within the clause.
"""
import argparse
import base64
import io
import json
import os
import pathlib
import re
import urllib.request
import wave

import numpy as np

ap = argparse.ArgumentParser()
ap.add_argument("script")
ap.add_argument("out")
ap.add_argument("timing")
ap.add_argument("--speaker", default="shreya")
ap.add_argument("--pace", type=float, default=1.1)
a = ap.parse_args()
KEY = os.environ["SARVAM_API_KEY"]
SR = 24000


def tts(text):
    body = {"text": text, "target_language_code": "hi-IN", "model": "bulbul:v3", "speaker": a.speaker,
            "pace": a.pace, "speech_sample_rate": SR}
    req = urllib.request.Request("https://api.sarvam.ai/text-to-speech", data=json.dumps(body).encode(),
                                 headers={"api-subscription-key": KEY, "Content-Type": "application/json"})
    wav = base64.b64decode(json.load(urllib.request.urlopen(req, timeout=120))["audios"][0])
    w = wave.open(io.BytesIO(wav))
    assert w.getframerate() == SR and w.getsampwidth() == 2
    x = np.frombuffer(w.readframes(w.getnframes()), "<i2").astype(np.float32) / 32768
    if w.getnchannels() == 2:
        x = x.reshape(-1, 2).mean(axis=1)
    return x


def trim(x):
    thr = 0.02 * np.abs(x).max()
    idx = np.where(np.abs(x) > thr)[0]
    return x[max(0, idx[0] - int(0.01 * SR)) : idx[-1] + int(0.05 * SR)]


def weight(s):
    """Rough syllable weight: Devanagari letters ~1, matras 0, Latin letters ~0.36, pauses for punctuation."""
    w = 0.0
    for ch in s:
        o = ord(ch)
        if 0x0904 <= o <= 0x0939 or 0x0958 <= o <= 0x0961:
            w += 1.0
        elif 0x0900 <= o <= 0x097F:
            w += 0.0
        elif ch.isalpha():
            w += 0.36
        elif ch in ",":
            w += 1.6
        elif ch in "।.?!":
            w += 2.2
        elif ch == " ":
            w += 0.25
    return w


def pause_after(text):
    return 0.28 if text.strip().endswith(("।", "?", ".", "!")) else 0.14


out = pathlib.Path(a.out)
out.mkdir(parents=True, exist_ok=True)
lengths, words, chars = {}, {}, 0
for line in json.load(open(a.script)):
    parts, anchors, pos = [], [], 0.0
    for i, clause in enumerate(line["clauses"]):
        marks = [(m.group(1), m.start()) for m in re.finditer(r"\{([^}]+)\}", clause)]
        plain = re.sub(r"\{[^}]+\}", "", clause)
        chars += len(plain)
        x = trim(tts(plain))
        if i > 0:
            g = pause_after(line["clauses"][i - 1])
            parts.append(np.zeros(int(g * SR), np.float32))
            pos += g
        dur = len(x) / SR
        total = weight(plain) or 1
        stripped = 0
        for name, idx in marks:
            before = re.sub(r"\{[^}]+\}", "", clause[:idx])
            t = pos + dur * weight(before) / total
            anchors.append([name, round(t, 3), round(t + 0.3, 3)])
        parts.append(x)
        pos += dur
    full = np.concatenate(parts)
    pcm = (np.clip(full, -1, 1) * 32767).astype("<i2").tobytes()
    with wave.open(str(out / f"{line['id']}.wav"), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(pcm)
    lengths[line["id"]] = round(len(full) / SR, 3)
    words[line["id"]] = anchors
    print(f"{line['id']:8s} {lengths[line['id']]:5.2f}s  " + " ".join(f"{n}@{s}" for n, s, _ in anchors))
json.dump(lengths, open(out / "lengths.json", "w"), indent=1)
pathlib.Path(a.timing).write_text(
    "// generated by explainer/voice_sarvam.py\nwindow.VO_TIMING = " + json.dumps({"lengths": lengths, "words": words}, ensure_ascii=False) + ";\n"
)
print(f"total speech {sum(lengths.values()):.2f} s, {chars} characters sent -> {a.timing}")
