"""Word timings for the recorded voice, in the script's own words.

    python3 motion/align.py out/motion-vo            # reads <id>.wav for every line in motion/script.json

Each line is transcribed with faster-whisper (word timestamps) and the heard words are aligned to the script
tokens (difflib on normalised text); tokens the recogniser split or misheard are interpolated between their
matched neighbours. The picture keys on script words, so a misheard "BotLane" can't break a cue.
Writes motion/timing.js (window.VO_TIMING) and <dir>/lengths.json.
"""
import difflib
import json
import pathlib
import re
import sys
import wave

HERE = pathlib.Path(__file__).resolve().parent
vo = pathlib.Path(sys.argv[1])
script = json.load(open(HERE / "script.json"))
norm = lambda s: re.sub(r"[^a-z0-9]", "", s.lower())

from faster_whisper import WhisperModel  # noqa: E402

model = WhisperModel("base.en", compute_type="int8")
lengths, words, texts = {}, {}, {}
for line in script:
    path = vo / f"{line['id']}.wav"
    with wave.open(str(path)) as wf:
        lengths[line["id"]] = round(wf.getnframes() / wf.getframerate(), 3)
    segs, _ = model.transcribe(str(path), beam_size=5, word_timestamps=True)
    heard = [(w.word.strip(), w.start, w.end) for s in segs for w in s.words]
    toks = line["text"].split()
    a = [norm(t) for t in toks]
    b = [norm(h[0]) for h in heard]
    times = [None] * len(toks)
    for blk in difflib.SequenceMatcher(None, a, b, autojunk=False).get_matching_blocks():
        for k in range(blk.size):
            times[blk.a + k] = (heard[blk.b + k][1], heard[blk.b + k][2])
    # interpolate the gaps (split words, "BotLane" heard as "Bot Lane", numbers)
    known = [i for i, v in enumerate(times) if v]
    for i in range(len(toks)):
        if times[i]:
            continue
        lo = max([k for k in known if k < i], default=None)
        hi = min([k for k in known if k > i], default=None)
        t0 = times[lo][1] if lo is not None else 0.0
        t1 = times[hi][0] if hi is not None else lengths[line["id"]]
        n0 = lo if lo is not None else -1
        n1 = hi if hi is not None else len(toks)
        f0, f1 = (i - n0 - 1) / (n1 - n0 - 1), (i - n0) / (n1 - n0 - 1)
        times[i] = (t0 + (t1 - t0) * f0, t0 + (t1 - t0) * f1)
    words[line["id"]] = [[tok, round(s, 3), round(e, 3)] for tok, (s, e) in zip(toks, times)]
    texts[line["id"]] = line["text"]
    print(f"{line['id']:8s} {lengths[line['id']]:5.2f}s  matched {len(known)}/{len(toks)}  heard: {' '.join(h[0] for h in heard)}")
json.dump(lengths, open(vo / "lengths.json", "w"), indent=1)
(HERE / "timing.js").write_text("// generated by motion/align.py\nwindow.VO_TIMING = " + json.dumps({"lengths": lengths, "words": words, "script": texts}) + ";\n")
print("total speech", round(sum(lengths.values()), 2), "s")
